# Generated by Django 4.2.13 on 2024-07-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ("-system", "type", "name"), "verbose_name": "Unit", "verbose_name_plural": "Units"},
        ),
    ]
