---
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--no-ensure-ascii, --autofix]
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: check-case-conflict
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.35.1'
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: [--disable, MD013]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.8.0'
    hooks:
      - id: eslint
        args: [--fix]
        types: [javascript, ts, vue]
        additional_dependencies:
          - "eslint@^9.8.0"
          - "@eslint/js@^9.8.0"
          - "eslint-config-prettier@^9.1.0"
          - "eslint-plugin-prettier@^5.2.1"
          - "prettier@^3.3.3"
          - "typescript-eslint@^8.0.0"
