---
exclude: ^(node_modules|static)/.+$
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--no-ensure-ascii, --autofix]
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: check-case-conflict
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.20.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.35.1'
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: [--disable, MD013]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "django-admin-interface"
          - "django-admin-sortable2"
          - "django-colorfield"
          - "django-breeze"
          - "django-environ"
          - "django-extensions"
          - "django-cachalot"
          - "django-ltree-2"
          - "django-modeltranslation"
          - "djangorestframework"
          - "easy-thumbnails"
          - "pillow"
          - "pint"
          - "recipe-scrapers>=15.0.0"
          - "django-stubs-ext"
          - "django-stubs"
          - "git+https://github.com/typeddjango/djangorestframework-stubs@master"
          - "pytest"
          - "types-requests"
          - "types-pyyaml"
  - repo: local
    hooks:
      - id: eslint
        language: system
        name: Run ESLint
        entry: yarn eslint --fix
        types: [file]
        files: \.(ts|js|vue)$
