---
services:
    django:
        container_name: recipe-backend
        build:
            context: ./
            args:
                - DEV_MODE=true
                - UID=${UID:-1000}
                - GID=${GID:-1000}
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/app
        expose:
            - "8000"
            - "5173"
        ports:
            - "8000:8000"
            - "5173:5173"
        env_file:
            - ./.env
        depends_on:
            db:
                condition: service_healthy
    db:
        container_name: recipe-db
        image: postgres:17-alpine
        healthcheck:
            test: [
                "CMD-SHELL",
                "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",
            ]
            start_period: 20s
            interval: 10s
            retries: 5
            timeout: 5s
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - ./.env

volumes:
    postgres-data:
