# Generated by Django 4.2.13 on 2024-06-22 01:16

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        help_text="Maximum 150 characters",
                        max_length=150,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Maximum 150 characters",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        help_text="Maximum 150 characters",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        help_text="Maximum 150 characters",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                ("name_plural", models.CharField(blank=True, max_length=150, null=True)),
                ("name_plural_en", models.CharField(blank=True, max_length=150, null=True)),
                ("name_plural_fr", models.CharField(blank=True, max_length=150, null=True)),
                ("name_plural_ja", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Automatically generated from the name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        help_text="Automatically generated from the name",
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "slug_fr",
                    models.SlugField(
                        help_text="Automatically generated from the name",
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "slug_ja",
                    models.SlugField(
                        help_text="Automatically generated from the name",
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to="images/categories/",
                        verbose_name="Thumbnail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
    ]
