# Generated by Django 4.2.13 on 2024-07-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingredient_qualifier_alter_userrating_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritioninformation",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition",
                to="recipes.recipe",
                verbose_name="Recipe",
            ),
        ),
    ]
