# Generated by Django 4.2.14 on 2024-08-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
        ("recipes", "0006_nutritioninformation_potassium_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="category",
            name="numchild",
        ),
        migrations.RemoveField(
            model_name="category",
            name="path",
        ),
        migrations.AddField(
            model_name="category",
            name="sub_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_categories",
                to="recipes.category",
                verbose_name="Sub-categories",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="top_level",
            field=models.BooleanField(
                default=False,
                help_text="This is one of the top level categories.",
                verbose_name="Top level",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="food.food",
                verbose_name="Food",
            ),
        ),
    ]
