# Generated by Django 4.2.14 on 2024-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_recipe_favourited_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientgroup",
            options={
                "ordering": ("order",),
                "verbose_name": "Ingredient Group",
                "verbose_name_plural": "Ingredient Groups",
            },
        ),
        migrations.AddField(
            model_name="ingredientgroup",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Order"),
        ),
    ]
