# Generated by Django 4.2.14 on 2024-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_ingredientgroup_options_ingredientgroup_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="amount_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=10,
                null=True,
                verbose_name="Max Amount",
            ),
        ),
    ]
