# Generated by Django 4.2.14 on 2024-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_ingredient_amount_alter_ingredient_amount_max"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_categories",
        ),
        migrations.AddField(
            model_name="category",
            name="parent_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="sub_categories",
                to="recipes.category",
                verbose_name="Parent-categories",
            ),
        ),
    ]
