# Generated by Django 4.2.14 on 2024-08-13 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0011_remove_category_sub_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_ja",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("user", "recipe")},
        ),
    ]
