# Generated by Django 4.2.15 on 2024-08-23 19:37
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations
import django_ltree.fields

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.models import QuerySet
    from recipe_repo.recipes.models import Category


def generate_sub_category_paths(parent_path: str, categories: QuerySet[Category]) -> None:
    for sub_category in categories:
        sub_category.path = f"{parent_path}.{sub_category.slug_en.replace('-', '_')}"
        sub_category.save()
        generate_sub_category_paths(sub_category.path, sub_category.sub_categories.all())


def generate_paths(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Category = apps.get_model("recipes", "Category")

    for category in Category.objects.filter(parent_categories__isnull=True):
        category.path = category.slug_en.replace("-", "_")
        category.save()
        generate_sub_category_paths(category.path, category.sub_categories.all())


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_description_en_recipe_description_fr_and_more"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION ltree", migrations.RunSQL.noop),
        migrations.AddField(
            model_name="category",
            name="path",
            field=django_ltree.fields.PathField(unique=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_paths, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="category",
            name="path",
            field=django_ltree.fields.PathField(unique=True),
            preserve_default=False,
        ),
    ]
