# Generated by Django 5.1.14 on 2025-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_userrating_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug_en",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug_fr",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug_ja",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ingredientgroup",
            unique_together={("name", "recipe"), ("name_en", "recipe"), ("name_fr", "recipe"), ("name_ja", "recipe")},
        ),
    ]
