# Generated by Django 4.2.15 on 2024-08-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_userrating_unique_together_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_recipes",
            field=models.ManyToManyField(
                related_name="favourited_by",
                to="recipes.recipe",
                verbose_name="Favourite Recipes",
            ),
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(0, "☆☆☆☆☆"), (1, "★☆☆☆☆"), (2, "★★☆☆☆"), (3, "★★★☆☆"), (4, "★★★★☆"), (5, "★★★★★")],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Rating",
                "verbose_name_plural": "User Ratings",
                "unique_together": {("user", "recipe")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="rated_recipes",
            field=models.ManyToManyField(
                related_name="rated_by",
                through="users.UserRating",
                to="recipes.recipe",
                verbose_name="Rated recipes",
            ),
        ),
    ]
