# Generated by Django 4.2.13 on 2024-06-21 01:18

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Photo",
            ),
        ),
    ]
