# Generated by Django 4.2.13 on 2024-07-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
