# Generated by Django 4.2.13 on 2024-07-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="Name")),
                ("name_en", models.CharField(max_length=150, null=True, unique=True, verbose_name="Name")),
                ("name_fr", models.CharField(max_length=150, null=True, unique=True, verbose_name="Name")),
                ("name_ja", models.CharField(max_length=150, null=True, unique=True, verbose_name="Name")),
                ("name_plural", models.CharField(blank=True, max_length=150, null=True, verbose_name="Plural Name")),
                ("name_plural_en", models.CharField(blank=True, max_length=150, null=True, verbose_name="Plural Name")),
                ("name_plural_fr", models.CharField(blank=True, max_length=150, null=True, verbose_name="Plural Name")),
                ("name_plural_ja", models.CharField(blank=True, max_length=150, null=True, verbose_name="Plural Name")),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Food",
            },
        ),
    ]
