# Generated by Django 4.2.14 on 2024-08-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ("name",), "verbose_name": "Food Item", "verbose_name_plural": "Food Items"},
        ),
    ]
