# Generated by Django 4.2.15 on 2024-08-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_migrate_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="categorytype",
            options={"ordering": ("name",), "verbose_name": "Category Type", "verbose_name_plural": "Category types"},
        ),
    ]
