# Generated by Django 5.1.14 on 2025-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_squashed_0003_alter_category_options_alter_categorytype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_en",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_fr",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_ja",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="slug_en",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="slug_fr",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="slug_ja",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Automatically generated from the name",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
